services:
  backend:
    build:
      target: prod
    environment:
      APP_MODE: prod
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      target: prod
    ports:
      - "80:80"
    restart: unless-stopped
